/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login.View;

import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Teles
 */
public class AvaliacoesView extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalView
     */
    public AvaliacoesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAvaliacoes = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelMedidas = new javax.swing.JLabel();
        jTextFieldInstrutor = new javax.swing.JTextField();
        jTextFieldObservacoes = new javax.swing.JTextField();
        jLabelInstrutor = new javax.swing.JLabel();
        jLabelAluno = new javax.swing.JLabel();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jTextFieldImc = new javax.swing.JTextField();
        jLabelObervacoes = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jLabelImc = new javax.swing.JLabel();
        jLabelDataAvaliacao2 = new javax.swing.JLabel();
        jTextFieldDataAvaliacao1 = new javax.swing.JTextField();
        jLabelAltura1 = new javax.swing.JLabel();
        jTextFieldAltura1 = new javax.swing.JTextField();
        jLabelPeso1 = new javax.swing.JLabel();
        jTextFieldPeso1 = new javax.swing.JTextField();
        jLabelImagemFundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAvaliacoes.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabelAvaliacoes.setText("Avaliações");
        getContentPane().add(jLabelAvaliacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        jButtonVoltar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVoltar.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 150, 50));

        jButtonCancelar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 720, 150, 50));

        jLabelMedidas.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelMedidas.setText("medidas corporais");
        getContentPane().add(jLabelMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 220, -1));
        getContentPane().add(jTextFieldInstrutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 560, 30));
        getContentPane().add(jTextFieldObservacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 660, 140));

        jLabelInstrutor.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelInstrutor.setText("Instrutor");
        getContentPane().add(jLabelInstrutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 240, -1));

        jLabelAluno.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelAluno.setText("Aluno");
        getContentPane().add(jLabelAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 70, -1));
        getContentPane().add(jTextFieldNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 560, 30));
        getContentPane().add(jTextFieldImc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 100, 30));

        jLabelObervacoes.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelObervacoes.setText("Observações");
        getContentPane().add(jLabelObervacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 160, -1));

        jButtonSalvar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalvar.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 720, 150, 50));

        jLabelImc.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        jLabelImc.setText("IMC");
        getContentPane().add(jLabelImc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 50, -1));

        jLabelDataAvaliacao2.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelDataAvaliacao2.setText("Data da avaliação");
        getContentPane().add(jLabelDataAvaliacao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 190, -1));
        getContentPane().add(jTextFieldDataAvaliacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 100, 30));

        jLabelAltura1.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelAltura1.setText("Altura (cm)");
        getContentPane().add(jLabelAltura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 120, -1));
        getContentPane().add(jTextFieldAltura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 100, 30));

        jLabelPeso1.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelPeso1.setText("Peso (kg)");
        getContentPane().add(jLabelPeso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 120, -1));
        getContentPane().add(jTextFieldPeso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 100, 30));

        jLabelImagemFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abstract-silhouette-bodybuilder-gym-logo-white-background-bodybuilder-training-vector-illustration-abstract-silhouette-139642649.jpg"))); // NOI18N
        getContentPane().add(jLabelImagemFundoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        MenuPrincipalView telaMenuPrincipal = new MenuPrincipalView();
        telaMenuPrincipal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        JOptionPane.showMessageDialog(null,"Operação cancelada!");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        JOptionPane.showMessageDialog(null,"Operação salva com sucesso!");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvaliacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvaliacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvaliacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvaliacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvaliacoesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelAltura1;
    private javax.swing.JLabel jLabelAluno;
    private javax.swing.JLabel jLabelAvaliacoes;
    private javax.swing.JLabel jLabelDataAvaliacao2;
    private javax.swing.JLabel jLabelImagemFundoTela;
    private javax.swing.JLabel jLabelImc;
    private javax.swing.JLabel jLabelInstrutor;
    private javax.swing.JLabel jLabelMedidas;
    private javax.swing.JLabel jLabelObervacoes;
    private javax.swing.JLabel jLabelPeso1;
    private javax.swing.JTextField jTextFieldAltura1;
    private javax.swing.JTextField jTextFieldDataAvaliacao1;
    private javax.swing.JTextField jTextFieldImc;
    private javax.swing.JTextField jTextFieldInstrutor;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    private javax.swing.JTextField jTextFieldObservacoes;
    private javax.swing.JTextField jTextFieldPeso1;
    // End of variables declaration//GEN-END:variables
}
