/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login.View;

import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Teles
 */
public class CadastrarFuncionarioView extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalView
     */
    public CadastrarFuncionarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroFuncionario = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelGenero = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelCpf1 = new javax.swing.JLabel();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jLabelNomeCompleto2 = new javax.swing.JLabel();
        jTextFieldNomeCompleto2 = new javax.swing.JTextField();
        jLabelRua1 = new javax.swing.JLabel();
        jTextFieldRua1 = new javax.swing.JTextField();
        jLabelBairro1 = new javax.swing.JLabel();
        jTextFieldBairro1 = new javax.swing.JTextField();
        jLabelCidade1 = new javax.swing.JLabel();
        jTextFieldCidade1 = new javax.swing.JTextField();
        jLabelCargo = new javax.swing.JLabel();
        jTextFieldTelefone1 = new javax.swing.JTextField();
        jLabelTelefone2 = new javax.swing.JLabel();
        jTextFieldTelefone2 = new javax.swing.JTextField();
        jLabelData1 = new javax.swing.JLabel();
        jComboBoxGenero1 = new javax.swing.JComboBox<>();
        jLabelTurno1 = new javax.swing.JLabel();
        jComboBoxTurno1 = new javax.swing.JComboBox<>();
        jButtonSalvar1 = new javax.swing.JButton();
        jLabelImagemFundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCadastroFuncionario.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabelCadastroFuncionario.setText("Cadastro Funcionário");
        getContentPane().add(jLabelCadastroFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        jButtonVoltar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVoltar.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 150, 50));

        jButtonCancelar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 720, 150, 50));

        jLabelGenero.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelGenero.setText("Gênero");
        getContentPane().add(jLabelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 80, -1));
        getContentPane().add(jTextFieldCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 240, 30));

        jLabelEmail.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelEmail.setText("E-mail");
        getContentPane().add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 100, -1));
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 280, 30));

        jLabelCpf1.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelCpf1.setText("CPF");
        getContentPane().add(jLabelCpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 60, -1));

        jComboBoxCargo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recepcionista", "Instrutor", "Gerente" }));
        getContentPane().add(jComboBoxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 640, 170, -1));

        jLabelNomeCompleto2.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelNomeCompleto2.setText("Nome Completo");
        getContentPane().add(jLabelNomeCompleto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 230, -1));
        getContentPane().add(jTextFieldNomeCompleto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 560, 30));

        jLabelRua1.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelRua1.setText("Rua");
        getContentPane().add(jLabelRua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 50, -1));
        getContentPane().add(jTextFieldRua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 560, 30));

        jLabelBairro1.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelBairro1.setText("Bairro");
        getContentPane().add(jLabelBairro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 70, -1));
        getContentPane().add(jTextFieldBairro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 560, 30));

        jLabelCidade1.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelCidade1.setText("Cidade");
        getContentPane().add(jLabelCidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 80, -1));
        getContentPane().add(jTextFieldCidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 280, 30));

        jLabelCargo.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelCargo.setText("Cargo");
        getContentPane().add(jLabelCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, 160, -1));
        getContentPane().add(jTextFieldTelefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 100, 30));

        jLabelTelefone2.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelTelefone2.setText("Telefone");
        getContentPane().add(jLabelTelefone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 100, -1));
        getContentPane().add(jTextFieldTelefone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 280, 30));

        jLabelData1.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelData1.setText("Data de inicio");
        getContentPane().add(jLabelData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 160, -1));

        jComboBoxGenero1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBoxGenero1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", " " }));
        getContentPane().add(jComboBoxGenero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, -1));

        jLabelTurno1.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelTurno1.setText("Turno");
        getContentPane().add(jLabelTurno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 160, -1));

        jComboBoxTurno1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBoxTurno1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Noturno" }));
        getContentPane().add(jComboBoxTurno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 640, 130, -1));

        jButtonSalvar1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalvar1.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonSalvar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar1.setText("Salvar");
        jButtonSalvar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 720, 150, 50));

        jLabelImagemFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abstract-silhouette-bodybuilder-gym-logo-white-background-bodybuilder-training-vector-illustration-abstract-silhouette-139642649.jpg"))); // NOI18N
        getContentPane().add(jLabelImagemFundoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        MenuPrincipalView telaMenuPrincipal = new MenuPrincipalView();
        telaMenuPrincipal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        JOptionPane.showMessageDialog(null,"Operação cancelada!");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvar1ActionPerformed
        JOptionPane.showMessageDialog(null,"Novo funcionário cadastrado com sucesso!");
    }//GEN-LAST:event_jButtonSalvar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFuncionarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar1;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JComboBox<String> jComboBoxGenero1;
    private javax.swing.JComboBox<String> jComboBoxTurno1;
    private javax.swing.JLabel jLabelBairro1;
    private javax.swing.JLabel jLabelCadastroFuncionario;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCidade1;
    private javax.swing.JLabel jLabelCpf1;
    private javax.swing.JLabel jLabelData1;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelImagemFundoTela;
    private javax.swing.JLabel jLabelNomeCompleto2;
    private javax.swing.JLabel jLabelRua1;
    private javax.swing.JLabel jLabelTelefone2;
    private javax.swing.JLabel jLabelTurno1;
    private javax.swing.JTextField jTextFieldBairro1;
    private javax.swing.JTextField jTextFieldCidade1;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNomeCompleto2;
    private javax.swing.JTextField jTextFieldRua1;
    private javax.swing.JTextField jTextFieldTelefone1;
    private javax.swing.JTextField jTextFieldTelefone2;
    // End of variables declaration//GEN-END:variables
}
