/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login.View;

import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Teles
 */
public class LancarPagamentoView extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalView
     */
    public LancarPagamentoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLancarPagamento = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelDataVencimento = new javax.swing.JLabel();
        jLabelBuscarAluno = new javax.swing.JLabel();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jTextFieldDataVencimento = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jComboBoxFormaPagamento = new javax.swing.JComboBox<>();
        jLabelFormaPagamento = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jLabelDataPagamento = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabelDataStatus = new javax.swing.JLabel();
        jTextFieldDataPagamento = new javax.swing.JTextField();
        jLabelImagemFundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLancarPagamento.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabelLancarPagamento.setText("Lançar Pagamento");
        getContentPane().add(jLabelLancarPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        jButtonVoltar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVoltar.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 150, 50));

        jButtonCancelar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 720, 150, 50));

        jLabelDataVencimento.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelDataVencimento.setText("Data de Vencimento");
        getContentPane().add(jLabelDataVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 230, -1));

        jLabelBuscarAluno.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelBuscarAluno.setText("Buscar Aluno (CPF)");
        getContentPane().add(jLabelBuscarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 230, -1));
        getContentPane().add(jTextFieldNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 560, 30));
        getContentPane().add(jTextFieldDataVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 110, 40));

        jButtonSalvar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalvar.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 720, 150, 50));

        jComboBoxFormaPagamento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBoxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Pix", "Cartão", " " }));
        getContentPane().add(jComboBoxFormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 180, 40));

        jLabelFormaPagamento.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelFormaPagamento.setText("Forma de Pagamento");
        getContentPane().add(jLabelFormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 230, -1));

        jLabelValor.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelValor.setText("Valor");
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 70, -1));
        getContentPane().add(jTextFieldStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 110, 40));

        jLabelDataPagamento.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelDataPagamento.setText("Data de Pagamento");
        getContentPane().add(jLabelDataPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 230, -1));
        getContentPane().add(jTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 110, 40));

        jLabelDataStatus.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabelDataStatus.setText("Status");
        getContentPane().add(jLabelDataStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 70, -1));
        getContentPane().add(jTextFieldDataPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 110, 40));

        jLabelImagemFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abstract-silhouette-bodybuilder-gym-logo-white-background-bodybuilder-training-vector-illustration-abstract-silhouette-139642649.jpg"))); // NOI18N
        getContentPane().add(jLabelImagemFundoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        MenuPrincipalView telaMenuPrincipal = new MenuPrincipalView();
        telaMenuPrincipal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        JOptionPane.showMessageDialog(null,"Operação cancelada!");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        JOptionPane.showMessageDialog(null,"Novo pagamento adicionado com sucesso!");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LancarPagamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LancarPagamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LancarPagamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LancarPagamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LancarPagamentoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxFormaPagamento;
    private javax.swing.JLabel jLabelBuscarAluno;
    private javax.swing.JLabel jLabelDataPagamento;
    private javax.swing.JLabel jLabelDataStatus;
    private javax.swing.JLabel jLabelDataVencimento;
    private javax.swing.JLabel jLabelFormaPagamento;
    private javax.swing.JLabel jLabelImagemFundoTela;
    private javax.swing.JLabel jLabelLancarPagamento;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JTextField jTextFieldDataPagamento;
    private javax.swing.JTextField jTextFieldDataVencimento;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
