/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login.View;

/**
 *
 * @author Gabriel Teles
 */
public class MenuPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalView
     */
    public MenuPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMenuPrincipal = new javax.swing.JLabel();
        jButtonAlunos = new javax.swing.JButton();
        jButtonFuncionarios = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonAvaliacoes = new javax.swing.JButton();
        jButtonCadastrarFuncionario = new javax.swing.JButton();
        jButtonPagamentos = new javax.swing.JButton();
        jButtonAgendarAvaliacao = new javax.swing.JButton();
        jButtonDespesas = new javax.swing.JButton();
        jButtonLancarPagamento = new javax.swing.JButton();
        jButtonSairDoSistema = new javax.swing.JButton();
        jButtonAdicionarDespesas = new javax.swing.JButton();
        jButtonCaixa = new javax.swing.JButton();
        jLabelImagemFundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMenuPrincipal.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabelMenuPrincipal.setText("Menu Principal");
        getContentPane().add(jLabelMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        jButtonAlunos.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAlunos.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonAlunos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAlunos.setText("Alunos");
        jButtonAlunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlunosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 260, 80));

        jButtonFuncionarios.setBackground(new java.awt.Color(0, 0, 0));
        jButtonFuncionarios.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFuncionarios.setText("Funcionários");
        jButtonFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 260, 80));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cadastrar Aluno");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, 80));

        jButtonAvaliacoes.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAvaliacoes.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonAvaliacoes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAvaliacoes.setText("Avaliações");
        jButtonAvaliacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvaliacoesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAvaliacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 260, 80));

        jButtonCadastrarFuncionario.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCadastrarFuncionario.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonCadastrarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastrarFuncionario.setText("Cadastrar Funcionário");
        jButtonCadastrarFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 260, 80));

        jButtonPagamentos.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPagamentos.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonPagamentos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPagamentos.setText("Pagamentos");
        jButtonPagamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagamentosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPagamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 260, 80));

        jButtonAgendarAvaliacao.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAgendarAvaliacao.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonAgendarAvaliacao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgendarAvaliacao.setText("Agendar Avaliação");
        jButtonAgendarAvaliacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgendarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarAvaliacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgendarAvaliacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 80));

        jButtonDespesas.setBackground(new java.awt.Color(0, 0, 0));
        jButtonDespesas.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonDespesas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDespesas.setText("Pagamentos");
        jButtonDespesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDespesasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 260, 80));

        jButtonLancarPagamento.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLancarPagamento.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonLancarPagamento.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLancarPagamento.setText("Lançar Pagamento");
        jButtonLancarPagamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLancarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLancarPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLancarPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 260, 80));

        jButtonSairDoSistema.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSairDoSistema.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonSairDoSistema.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSairDoSistema.setText("Sair do Sistema");
        jButtonSairDoSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSairDoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairDoSistemaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSairDoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 690, 260, 80));

        jButtonAdicionarDespesas.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAdicionarDespesas.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonAdicionarDespesas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdicionarDespesas.setText("Adicionar Despesas");
        jButtonAdicionarDespesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarDespesasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdicionarDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 260, 80));

        jButtonCaixa.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCaixa.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jButtonCaixa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCaixa.setText("Caixa");
        jButtonCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaixaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 260, 80));

        jLabelImagemFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abstract-silhouette-bodybuilder-gym-logo-white-background-bodybuilder-training-vector-illustration-abstract-silhouette-139642649.jpg"))); // NOI18N
        getContentPane().add(jLabelImagemFundoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlunosActionPerformed

    private void jButtonFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFuncionariosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvaliacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAvaliacoesActionPerformed

    private void jButtonCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastrarFuncionarioActionPerformed

    private void jButtonPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPagamentosActionPerformed

    private void jButtonAgendarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarAvaliacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgendarAvaliacaoActionPerformed

    private void jButtonDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDespesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDespesasActionPerformed

    private void jButtonLancarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLancarPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLancarPagamentoActionPerformed

    private void jButtonSairDoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairDoSistemaActionPerformed
        SairSistemaView telaSairDoSistema = new SairSistemaView();
        telaSairDoSistema.setVisible(true);
    }//GEN-LAST:event_jButtonSairDoSistemaActionPerformed

    private void jButtonAdicionarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarDespesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdicionarDespesasActionPerformed

    private void jButtonCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdicionarDespesas;
    private javax.swing.JButton jButtonAgendarAvaliacao;
    private javax.swing.JButton jButtonAlunos;
    private javax.swing.JButton jButtonAvaliacoes;
    private javax.swing.JButton jButtonCadastrarFuncionario;
    private javax.swing.JButton jButtonCaixa;
    private javax.swing.JButton jButtonDespesas;
    private javax.swing.JButton jButtonFuncionarios;
    private javax.swing.JButton jButtonLancarPagamento;
    private javax.swing.JButton jButtonPagamentos;
    private javax.swing.JButton jButtonSairDoSistema;
    private javax.swing.JLabel jLabelImagemFundoTela;
    private javax.swing.JLabel jLabelMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
